language: bash
services: docker
sudo: required

install:
  - docker run --rm --privileged multiarch/qemu-user-static:register

script:
  - docker build -t napnap75/rpi-alpine-base:v3.3 .
  - docker tag napnap75/rpi-alpine-base:v3.3 napnap75/rpi-alpine-base:latest
  - docker images

deploy:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push napnap75/rpi-alpine-base:v3.3
  
