language: bash
services: docker
sudo: required

env:
  - VERSION=3.4
  - VERSION=3.5
  - VERSION=edge

install:  
  - docker run --rm --privileged multiarch/qemu-user-static:register

script:
# Download
  - curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v2.6.0/qemu-arm-static.tar.gz && tar xzf qemu-arm-static.tar.gz
# Build
  - docker build -t napnap75/rpi-alpine-base:${VERSION} -f ${VERSION}/Dockerfile .
# Check
  - docker images
  - docker run --rm napnap75/rpi-alpine-base:${VERSION} uname -a

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push napnap75/rpi-alpine-base:${VERSION}
  - if [ "${VERSION}" = "3.5" ]; then docker tag napnap75/rpi-alpine-base:${VERSION} napnap75/rpi-alpine-base:latest ; docker push napnap75/rpi-alpine-base:latest ; fi
