language: bash
services: docker
sudo: required

notifications:
  slack:
    secure: 4QPtyjRm8yv/ygM+qFbpv5EO9kQpimqS+PT17z5I9WygOXSPAqjBPxpwnUtJGCTPtTYshRQNO3KEII27+JzhKOkR4Absn6WJ+TvwzehSjGT82YDAZRFV0H+RBrQvg57oNnm1TOcPdEjzhvJ57CrVIoCM9rverzZ/bLOM/+fcDeVO2vfiWUqmkpT9DScLq9WtISVBt53GifC586/fsIEIyNLi6SFw19G7qM9U/2Y5pjFUTuXij0Mnpn68/wVZPElAtcFV7tW/IWyCbnxgvBONrKkR5ZrhFjx3eVH1fZC56u76SjsYxNfQCuCXH35QNjoTwYDW9hwAAqqe+7EDbhhRdZID5CVnDpXFpcxTFLP7SJNyKiohJSiLVULKXR3wE+gRvXl82pj1TnKJNlO0bYSHWORm51IONmKto9k5xOCj4afim7ec5q9eiMG0pIYtA+STCkSBlvzdLM4eRRfp3ur06o9OyxWNfFQFkStOkYllsx187j+7aDqiNLX4/UbcP50drqR3QQz9bErHduzS5YznrpVYKUc/V3M7RT6kH0U4Oy1VhpprzhmtCrdki1IgV8lo2eTkd5R3729wKhY7s4yKKvMwBz8GSlhv36+d9I5O1SSeMsVN2giNWW8q+qcVqXUlEO5/DQBHs0MnBNvNEjDIz13uK7d/hcYdGYsHS9ft3CE=
    on_success: change
    
env:
  - VERSION=3.5
  - VERSION=3.6
  - VERSION=edge

# Install QEmu to allow Travis (on x86 systems) to build ARM images
install:
  - docker run --rm --privileged multiarch/qemu-user-static:register
  - curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v2.6.0/qemu-arm-static.tar.gz && tar xzf qemu-arm-static.tar.gz

# Build and test the image
script:
  - if [ "${VERSION}" != "edge" ]; then cat Dockerfile.source | sed "s/%VERSION%/${VERSION}/g" > Dockerfile.${VERSION} ; fi
  - docker build -t napnap75/rpi-alpine-base:${VERSION} -f Dockerfile.${VERSION} .
  - docker images
  - docker run --rm napnap75/rpi-alpine-base:${VERSION} uname -a

# If successful, push the images
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" ;
      docker push napnap75/rpi-alpine-base:${VERSION} ;
      if [ "${VERSION}" == "3.6" ]; then docker tag napnap75/rpi-alpine-base:${VERSION} napnap75/rpi-alpine-base:latest ; docker push napnap75/rpi-alpine-base:latest ; fi ;
    fi
