language: bash
services: docker
sudo: required

install:
  - git clone https://github.com/napnap75/rpi-alpine-base.git ~/rpi-alpine-base

before_script:
  - sudo apt-get --yes --no-install-recommends install binfmt-support qemu-user-static
  - echo ':arm:M::\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x28\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-arm-static:' | sudo tee -a /proc/sys/fs/binfmt_misc/register
  - env | sort

script:
  - image="napnap75/rpi-alpine-base:latest"
  - docker build -t "$image" .

after_script:
  - docker images
  
