language: bash
services: docker
sudo: required

install:
  - docker run --rm --privileged multiarch/qemu-user-static:register

script:
  - docker build -t napnap75/rpi-alpine-base:latest .
  - docker run --rm napnap75/rpi-alpine-base:latest bash -c env && uname -a
  - docker images

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push napnap75/rpi-alpine-base:latest
  - docker tag napnap75/rpi-alpine-base:latest napnap75/rpi-alpine-base:3.4
  - docker push napnap75/rpi-alpine-base:3.4
  - export CURRENTDATE=$(date +%y%m%d)
  - docker tag napnap75/rpi-alpine-base:latest napnap75/rpi-alpine-base:$CURRENTDATE
  - docker push napnap75/rpi-alpine-base:$CURRENTDATE
