# Builder image
FROM alpine:latest as builder

RUN apk add --no-cache curl \
  && curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v2.6.0/qemu-arm-static.tar.gz \
  && tar xzf qemu-arm-static.tar.gz

# Final image
FROM arm32v6/alpine:3.5

# Install QEmu to be able to build this image in Travis CI
COPY --from=builder qemu-arm-static /usr/bin/qemu-arm-static

# Install dependencies and set timezone
RUN echo -e "http://dl-4.alpinelinux.org/alpine/v3.5/main\nhttp://dl-4.alpinelinux.org/alpine/v3.5/community" > /etc/apk/repositories \
	&& apk add --no-cache bash tini su-exec alpine-conf tzdata \
	&& apk upgrade --no-cache \
	&& setup-timezone -z CET \
	&& apk del alpine-conf tzdata

# Add my own entry script to run as one user
ADD docker-entrypoint.sh /usr/sbin/docker-entrypoint.sh
RUN chmod +x /usr/sbin/docker-entrypoint.sh

# Set Tini as entrypoint 
ENTRYPOINT ["/sbin/tini", "--", "/usr/sbin/docker-entrypoint.sh"]
